language: ruby
rvm:
  - 2.5.3
  - 2.6.3
env:
  global:
    - CC_TEST_REPORTER_ID=4a8875ec1a4bd9cc55d9fe48779be866f90ac331155d039fa3d13b2a61b4fa9f
  matrix:
    - STRATEGY=array
    - STRATEGY=ltree
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
gemfile:
  - gemfiles/activerecord_5.1.5.gemfile
  - gemfiles/activerecord_5.2.0.gemfile
  - gemfiles/activerecord_6.0.0.gemfile
before_install: gem install bundler -v 1.10.6
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  postgresql: "9.6"
services:
  - postgresql
